version: 2

jobs:
  build:
      docker:
        - image: circleci/php:7.1-node-browsers

      working_directory: ~/laravel

      steps:
        - checkout

        - run:
            name: Updating Composer
            command: composer self-update
        - restore_cache:
            keys:
              - composer-v1-{{ checksum "composer.lock" }}
              - composer-v1-
        - run:
            name: Installing Composer dependencies
            command: composer install -n --prefer-dist
        - save_cache:
            key: composer-v1-{{ checksum "composer.lock" }}
            paths:
              - vendor

        - run:
            name: Running PHPUnit tests
            command: |
              mkdir -p ~/phpunit
              vendor/bin/phpunit --log-junit ~/phpunit/junit.xml
        - store_test_results:
            path: ~/phpunit
        - store_artifacts:
            path: ~/phpunit
